// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.2
// source: MessageDefine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgType int32

const (
	MsgType_ApiOrbitNormal       MsgType = 0
	MsgType_ApiOrbitCoordinate   MsgType = 1
	MsgType_ApiMarkerCoordinates MsgType = 2
	MsgType_ApiShowPicture       MsgType = 3
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "ApiOrbitNormal",
		1: "ApiOrbitCoordinate",
		2: "ApiMarkerCoordinates",
		3: "ApiShowPicture",
	}
	MsgType_value = map[string]int32{
		"ApiOrbitNormal":       0,
		"ApiOrbitCoordinate":   1,
		"ApiMarkerCoordinates": 2,
		"ApiShowPicture":       3,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_MessageDefine_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_MessageDefine_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_MessageDefine_proto_rawDescGZIP(), []int{0}
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type MsgType `protobuf:"varint,1,opt,name=Type,proto3,enum=MsgType" json:"Type,omitempty"`
	Data []byte  `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MessageDefine_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_MessageDefine_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_MessageDefine_proto_rawDescGZIP(), []int{0}
}

func (x *Msg) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_ApiOrbitNormal
}

func (x *Msg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Coordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longitude float32 `protobuf:"fixed32,1,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	Latitude  float32 `protobuf:"fixed32,2,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
}

func (x *Coordinate) Reset() {
	*x = Coordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MessageDefine_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coordinate) ProtoMessage() {}

func (x *Coordinate) ProtoReflect() protoreflect.Message {
	mi := &file_MessageDefine_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coordinate.ProtoReflect.Descriptor instead.
func (*Coordinate) Descriptor() ([]byte, []int) {
	return file_MessageDefine_proto_rawDescGZIP(), []int{1}
}

func (x *Coordinate) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Coordinate) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

type OrbitNormal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
}

func (x *OrbitNormal) Reset() {
	*x = OrbitNormal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MessageDefine_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrbitNormal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitNormal) ProtoMessage() {}

func (x *OrbitNormal) ProtoReflect() protoreflect.Message {
	mi := &file_MessageDefine_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitNormal.ProtoReflect.Descriptor instead.
func (*OrbitNormal) Descriptor() ([]byte, []int) {
	return file_MessageDefine_proto_rawDescGZIP(), []int{2}
}

func (x *OrbitNormal) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *OrbitNormal) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *OrbitNormal) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type OrbitCoordinate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coord *Coordinate `protobuf:"bytes,1,opt,name=Coord,proto3" json:"Coord,omitempty"`
}

func (x *OrbitCoordinate) Reset() {
	*x = OrbitCoordinate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MessageDefine_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrbitCoordinate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrbitCoordinate) ProtoMessage() {}

func (x *OrbitCoordinate) ProtoReflect() protoreflect.Message {
	mi := &file_MessageDefine_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrbitCoordinate.ProtoReflect.Descriptor instead.
func (*OrbitCoordinate) Descriptor() ([]byte, []int) {
	return file_MessageDefine_proto_rawDescGZIP(), []int{3}
}

func (x *OrbitCoordinate) GetCoord() *Coordinate {
	if x != nil {
		return x.Coord
	}
	return nil
}

type MarkerCoordinates struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coordinates []*Coordinate `protobuf:"bytes,1,rep,name=Coordinates,proto3" json:"Coordinates,omitempty"`
}

func (x *MarkerCoordinates) Reset() {
	*x = MarkerCoordinates{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MessageDefine_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MarkerCoordinates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkerCoordinates) ProtoMessage() {}

func (x *MarkerCoordinates) ProtoReflect() protoreflect.Message {
	mi := &file_MessageDefine_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkerCoordinates.ProtoReflect.Descriptor instead.
func (*MarkerCoordinates) Descriptor() ([]byte, []int) {
	return file_MessageDefine_proto_rawDescGZIP(), []int{4}
}

func (x *MarkerCoordinates) GetCoordinates() []*Coordinate {
	if x != nil {
		return x.Coordinates
	}
	return nil
}

type ShowPicture struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *ShowPicture) Reset() {
	*x = ShowPicture{}
	if protoimpl.UnsafeEnabled {
		mi := &file_MessageDefine_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowPicture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowPicture) ProtoMessage() {}

func (x *ShowPicture) ProtoReflect() protoreflect.Message {
	mi := &file_MessageDefine_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowPicture.ProtoReflect.Descriptor instead.
func (*ShowPicture) Descriptor() ([]byte, []int) {
	return file_MessageDefine_proto_rawDescGZIP(), []int{5}
}

func (x *ShowPicture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_MessageDefine_proto protoreflect.FileDescriptor

var file_MessageDefine_proto_rawDesc = []byte{
	0x0a, 0x13, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x37, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x1c, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x08, 0x2e, 0x4d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22, 0x46,
	0x0a, 0x0a, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x09, 0x4c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x4c, 0x61,
	0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x22, 0x37, 0x0a, 0x0b, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x4e,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x12, 0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a, 0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01,
	0x59, 0x12, 0x0c, 0x0a, 0x01, 0x5a, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x5a, 0x22,
	0x34, 0x0a, 0x0f, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61,
	0x74, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x22, 0x42, 0x0a, 0x11, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72, 0x43,
	0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x12, 0x2d, 0x0a, 0x0b, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0b, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x52, 0x0b, 0x43, 0x6f,
	0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x22, 0x21, 0x0a, 0x0b, 0x53, 0x68, 0x6f,
	0x77, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x2a, 0x63, 0x0a, 0x07,
	0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x41, 0x70, 0x69, 0x4f, 0x72,
	0x62, 0x69, 0x74, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x41,
	0x70, 0x69, 0x4f, 0x72, 0x62, 0x69, 0x74, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x70, 0x69, 0x4d, 0x61, 0x72, 0x6b, 0x65, 0x72,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x73, 0x10, 0x02, 0x12, 0x12, 0x0a,
	0x0e, 0x41, 0x70, 0x69, 0x53, 0x68, 0x6f, 0x77, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x10,
	0x03, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_MessageDefine_proto_rawDescOnce sync.Once
	file_MessageDefine_proto_rawDescData = file_MessageDefine_proto_rawDesc
)

func file_MessageDefine_proto_rawDescGZIP() []byte {
	file_MessageDefine_proto_rawDescOnce.Do(func() {
		file_MessageDefine_proto_rawDescData = protoimpl.X.CompressGZIP(file_MessageDefine_proto_rawDescData)
	})
	return file_MessageDefine_proto_rawDescData
}

var file_MessageDefine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_MessageDefine_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_MessageDefine_proto_goTypes = []interface{}{
	(MsgType)(0),              // 0: MsgType
	(*Msg)(nil),               // 1: Msg
	(*Coordinate)(nil),        // 2: Coordinate
	(*OrbitNormal)(nil),       // 3: OrbitNormal
	(*OrbitCoordinate)(nil),   // 4: OrbitCoordinate
	(*MarkerCoordinates)(nil), // 5: MarkerCoordinates
	(*ShowPicture)(nil),       // 6: ShowPicture
}
var file_MessageDefine_proto_depIdxs = []int32{
	0, // 0: Msg.Type:type_name -> MsgType
	2, // 1: OrbitCoordinate.Coord:type_name -> Coordinate
	2, // 2: MarkerCoordinates.Coordinates:type_name -> Coordinate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_MessageDefine_proto_init() }
func file_MessageDefine_proto_init() {
	if File_MessageDefine_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_MessageDefine_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MessageDefine_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MessageDefine_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrbitNormal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MessageDefine_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrbitCoordinate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MessageDefine_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MarkerCoordinates); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_MessageDefine_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowPicture); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_MessageDefine_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_MessageDefine_proto_goTypes,
		DependencyIndexes: file_MessageDefine_proto_depIdxs,
		EnumInfos:         file_MessageDefine_proto_enumTypes,
		MessageInfos:      file_MessageDefine_proto_msgTypes,
	}.Build()
	File_MessageDefine_proto = out.File
	file_MessageDefine_proto_rawDesc = nil
	file_MessageDefine_proto_goTypes = nil
	file_MessageDefine_proto_depIdxs = nil
}
