db_name: test
db_uri: mongodb://docker:mongopw@127.0.0.1:27017 
udp_port: 9191
satellite_tcp_port: 9192
speech_url: http://127.0.0.1:20001
db_topo_table_name: topo_table
db_vmcdata_table_name: vmcdata
db_sender_table_name: sender
