volumes:
  data:

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=docker
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
  myapp:
    image: star_atlas_server:latest 
    container_name: "star_atlas_server"
    platform: "linux/amd64"
    ports:
      - 9999:9999
      - 9191:9191/udp  # udp listener
